dependencies:
  - name: zookeeper
    version: "2.1.6"
    repository: "file://../hdfs-zookeeper-k8s"
    condition: condition.subchart.zookeeper
    tags:
      - ha
      - kerberos
  - name: hdfs-config-k8s
    version: "0.1.0"
    repository: "file://../hdfs-config-k8s"
    condition: condition.subchart.config
    tags:
      - ha
      - kerberos
  - name: hdfs-journalnode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-journalnode-k8s"
    condition: condition.subchart.journalnode
    tags:
      - ha
      - kerberos
  - name: hdfs-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-namenode-k8s"
    condition: condition.subchart.namenode
    tags:
      - ha
      - kerberos
  - name: hdfs-datanode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-datanode-k8s"
    condition: condition.subchart.datanode
    tags:
      - ha
      - kerberos
  - name: hdfs-client-k8s
    version: "0.1.0"
    repository: "file://../hdfs-client-k8s"
    condition: condition.subchart.client
    tags:
      - ha
      - kerberos
