## ------------------------------------------------------------------------------
## zookeeper:
## ------------------------------------------------------------------------------
zookeeper:
  ## Configure Zookeeper resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: ~

  persistence:
    ## zookeeper data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"

  ## The JVM heap size to allocate to Zookeeper
  env:
    ZK_HEAP_SIZE: 1G

  ## The number of zookeeper server to have in the quorum.
  replicaCount: 3

## ------------------------------------------------------------------------------
## hdfs-client-k8s:
## ------------------------------------------------------------------------------
hdfs-client-k8s:
  # Docker images information
  image:
    repository: uhopper/hadoop
    tag: 2.7.2
    pullPolicy: IfNotPresent

## ------------------------------------------------------------------------------
## hdfs-config-k8s:
## ------------------------------------------------------------------------------
hdfs-config-k8s:
  ## Custom hadoop config keys passed to the hdfs configmap as extra keys.
  customHadoopConfig:
    coreSite: {}
      ## Set config key and value pairs, e.g.
      # hadoop.http.authentication.type: kerberos

    hdfsSite: {}
      ## Set config key and value pairs, e.g.
      # dfs.datanode.use.datanode.hostname: "false"

## ------------------------------------------------------------------------------
## hdfs-journalnode-k8s:
## ------------------------------------------------------------------------------
hdfs-journalnode-k8s:
  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd
    accessMode: ReadWriteOnce
    size: 20Gi

  ## Node labels and tolerations for pod assignment
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Docker images information
  image:
    repository: uhopper/hadoop-namenode
    tag: 2.7.2
    pullPolicy: IfNotPresent
  
  initKeytabImage:
    repository: busybox
    tag: 1.27.1
    pullPolicy: IfNotPresent

## ------------------------------------------------------------------------------
## hdfs-namenode-k8s:
## ------------------------------------------------------------------------------
hdfs-namenode-k8s:
  ## Name of the namenode start script in the config map.
  namenodeStartScript: format-and-run.sh

  ## A namenode start script that can have user specified content.
  ## Can be used to conduct ad-hoc operation as specified by a user.
  ## To use this, also set the namenodeStartScript variable above
  ## to custom-run.sh.
  customRunScript: |
    #!/bin/bash -x
    echo Write your own script content!
    echo This message will disappear in 10 seconds.
    sleep 10

  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"

    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd

    accessMode: ReadWriteOnce

    size: 100Gi

  ## Node labels and tolerations for pod assignment
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Docker images information
  image:
    repository: uhopper/hadoop-namenode
    tag: 2.7.2
    pullPolicy: IfNotPresent

  initKeytabImage:
    repository: busybox
    tag: 1.27.1
    pullPolicy: IfNotPresent

## ------------------------------------------------------------------------------
## hdfs-datanode-k8s:
## ------------------------------------------------------------------------------
hdfs-datanode-k8s:
  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd
    accessMode: ReadWriteOnce
    size: 20Gi

  ## Node labels and tolerations for pod assignment
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Docker images information
  image:
    repository: uhopper/hadoop-datanode
    tag: 2.7.2
    pullPolicy: IfNotPresent
    
  initKeytabImage:
    repository: busybox
    tag: 1.27.1
    pullPolicy: IfNotPresent
    
  initJsvcImage:
    repository: mschlimb/jsvc
    tag: sha256:bf20eb9a319e9a2f87473d8da7418d21503a97528b932800b6b8417cd31e30ef
    pullPolicy: IfNotPresent

## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  #clusterDomain: cluster.local

  ## A list of the local disk directories on cluster nodes that will contain the datanode
  ## blocks. These paths will be mounted to the datanode as K8s HostPath volumes.
  ## In a command line, the list should be enclosed in '{' and '}'.
  ## e.g. --set "dataNodeHostPath={/hdfs-data,/hdfs-data1}"
  dataNodeHostPath:
    - /hdfs-data

  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ## The number of zookeeper server to have in the quorum.
  ## This should match zookeeper.replicaCount above
  zookeeperQuorumSize: 3

  ## Override zookeeper quorum address. Zookeeper is used for determining which namenode
  ## instance is active. Separated by the comma character.
  ##
  # zookeeperQuorumOverride: zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181,zk-2.zk-svc.default.svc.cluster.local:2181

  ## How many journal nodes to launch as a quorum.
  journalnodeQuorumSize: 3

  ## How many data nodes to launch.
  datanodeSize: 3

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

  ## Kerberos support.
  kerberos:
    ## Whether or not Kerberos support is enabled.
    enabled: false

    ## Effective only if Kerberos is enabled. Override th name of the k8s
    ## ConfigMap containing the kerberos config file.
    ##
    # configMapOverride: kerberos-config

    ## Effective only if Kerberos is enabled. Name of the kerberos config file inside
    ## the config map.
    configFileName: krb5.conf

    ## Required to be non-empty if Kerberos is enabled. Specify your Kerberos realm name.
    ## This should match the realm name in your Kerberos config file.
    realm: MYCOMPANY.COM

    ## Effective only if Kerberos is enabled. Enable protection of datanodes using
    ## the jsvc utility. See the reference doc at
    ## https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#Secure_DataNode
    jsvcEnabled: true

  ## Vault configuration to support secret injection.
  vault:
    ## Whether or not Vault secret injection is enabled. Mandatory if Kerberos is enabled
    enabled: false

    ## Vault role to get Vault secrets during secret injection
    role: default

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for high availability. Enabled by default.
  ha: true